#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="${SERVICE_NAME:-aperiodic-monotiles-generator}"
PROJECT_ID="${PROJECT_ID:-aperiodos}"
REGION="${REGION:-europe-west1}"
MAX_INSTANCES="${MAX_INSTANCES:-1}"
RENDER_DAILY_LIMIT="${RENDER_DAILY_LIMIT:-3}"
RENDER_GLOBAL_DAILY_LIMIT="${RENDER_GLOBAL_DAILY_LIMIT:-50}"
PUBLIC_APP_URL="${PUBLIC_APP_URL:-https://www.aperiodos.com}"
FIRESTORE_PROJECT_ID="${FIRESTORE_PROJECT_ID:-$PROJECT_ID}"
FIRESTORE_DATABASE_ID="${FIRESTORE_DATABASE_ID:-aperiodos-storage}"
DONATION_CURRENCY="${DONATION_CURRENCY:-eur}"
MIN_DONATION_CENTS="${MIN_DONATION_CENTS:-100}"
STRIPE_RENDER_CREDITS_PRICE_ID="${STRIPE_RENDER_CREDITS_PRICE_ID:-price_1U5NLC3SIDKPozJgE8ZCl9zy}"

# Secret values never belong in this script. These variables identify Secret
# Manager resources and pinned versions that Cloud Run exposes to the app.
STRIPE_API_KEY_SECRET="${STRIPE_API_KEY_SECRET:-aperiodos-stripe-live-api-key}"
STRIPE_API_KEY_VERSION="${STRIPE_API_KEY_VERSION:-1}"
STRIPE_WEBHOOK_SECRET_SECRET="${STRIPE_WEBHOOK_SECRET_SECRET:-aperiodos-stripe-live-webhook-secret}"
STRIPE_WEBHOOK_SECRET_VERSION="${STRIPE_WEBHOOK_SECRET_VERSION:-1}"
RENDER_QUOTA_SECRET_SECRET="${RENDER_QUOTA_SECRET_SECRET:-aperiodos-render-quota-secret}"
RENDER_QUOTA_SECRET_VERSION="${RENDER_QUOTA_SECRET_VERSION:-1}"
RENDER_CREDIT_SECRET_SECRET="${RENDER_CREDIT_SECRET_SECRET:-aperiodos-render-credit-secret}"
RENDER_CREDIT_SECRET_VERSION="${RENDER_CREDIT_SECRET_VERSION:-1}"
SENDGRID_API_KEY_SECRET="${SENDGRID_API_KEY_SECRET:-aperiodos-sendgrid-api-key}"
SENDGRID_API_KEY_VERSION="${SENDGRID_API_KEY_VERSION:-1}"
SENDGRID_FROM_EMAIL="${SENDGRID_FROM_EMAIL:-noreply@trainvent.com}"
SENDGRID_FROM_NAME="${SENDGRID_FROM_NAME:-Trainvent Aperiodos}"
SKIP_PUBLIC_IAM_UPDATE="${SKIP_PUBLIC_IAM_UPDATE:-0}"
APP_VERSION="${APP_VERSION:-${RELEASE_TAG:-development}}"

STRIPE_API_KEY_PATH="/secrets/stripe-api-key/value"
STRIPE_WEBHOOK_SECRET_PATH="/secrets/stripe-webhook-secret/value"
RENDER_QUOTA_SECRET_PATH="/secrets/render-quota-secret/value"
RENDER_CREDIT_SECRET_PATH="/secrets/render-credit-secret/value"
SENDGRID_API_KEY_PATH="/secrets/sendgrid-api-key/value"

RUNTIME_ENV_VARS="APP_VERSION=$APP_VERSION,STRIPE_MODE=live,PUBLIC_APP_URL=$PUBLIC_APP_URL,STRIPE_RENDER_CREDITS_PRICE_ID=$STRIPE_RENDER_CREDITS_PRICE_ID,DONATION_CURRENCY=$DONATION_CURRENCY,MIN_DONATION_CENTS=$MIN_DONATION_CENTS,FIRESTORE_PROJECT_ID=$FIRESTORE_PROJECT_ID,FIRESTORE_DATABASE_ID=$FIRESTORE_DATABASE_ID,RENDER_DAILY_LIMIT=$RENDER_DAILY_LIMIT,RENDER_GLOBAL_DAILY_LIMIT=$RENDER_GLOBAL_DAILY_LIMIT,STRIPE_SECRET_KEY_FILE=$STRIPE_API_KEY_PATH,STRIPE_WEBHOOK_SECRET_FILE=$STRIPE_WEBHOOK_SECRET_PATH,RENDER_QUOTA_SECRET_FILE=$RENDER_QUOTA_SECRET_PATH,RENDER_CREDIT_SECRET_FILE=$RENDER_CREDIT_SECRET_PATH,SENDGRID_API_KEY_FILE=$SENDGRID_API_KEY_PATH,SENDGRID_FROM_EMAIL=$SENDGRID_FROM_EMAIL,SENDGRID_FROM_NAME=$SENDGRID_FROM_NAME"
RUNTIME_SECRET_MOUNTS="$STRIPE_API_KEY_PATH=$STRIPE_API_KEY_SECRET:$STRIPE_API_KEY_VERSION,$STRIPE_WEBHOOK_SECRET_PATH=$STRIPE_WEBHOOK_SECRET_SECRET:$STRIPE_WEBHOOK_SECRET_VERSION,$RENDER_QUOTA_SECRET_PATH=$RENDER_QUOTA_SECRET_SECRET:$RENDER_QUOTA_SECRET_VERSION,$RENDER_CREDIT_SECRET_PATH=$RENDER_CREDIT_SECRET_SECRET:$RENDER_CREDIT_SECRET_VERSION,$SENDGRID_API_KEY_PATH=$SENDGRID_API_KEY_SECRET:$SENDGRID_API_KEY_VERSION"
LEGACY_SECRET_ENV_KEYS="STRIPE_SECRET_KEY,STRIPE_WEBHOOK_SECRET,RENDER_QUOTA_SECRET,RENDER_CREDIT_SECRET,SENDGRID_API_KEY"

require_secret_version() {
  local secret_name="$1"
  local secret_version="$2"
  if ! gcloud secrets versions describe "$secret_version" \
    --secret="$secret_name" \
    --project="$PROJECT_ID" >/dev/null; then
    echo "Missing or inaccessible Secret Manager version: $secret_name:$secret_version" >&2
    exit 1
  fi
}

require_secret_version "$STRIPE_API_KEY_SECRET" "$STRIPE_API_KEY_VERSION"
require_secret_version "$STRIPE_WEBHOOK_SECRET_SECRET" "$STRIPE_WEBHOOK_SECRET_VERSION"
require_secret_version "$RENDER_QUOTA_SECRET_SECRET" "$RENDER_QUOTA_SECRET_VERSION"
require_secret_version "$RENDER_CREDIT_SECRET_SECRET" "$RENDER_CREDIT_SECRET_VERSION"
require_secret_version "$SENDGRID_API_KEY_SECRET" "$SENDGRID_API_KEY_VERSION"

PUBLIC_ACCESS_ARGS=(--allow-unauthenticated)
if [[ "$SKIP_PUBLIC_IAM_UPDATE" == "1" ]]; then
  PUBLIC_ACCESS_ARGS=()
fi

gcloud run deploy "$SERVICE_NAME" \
  --source . \
  --region="$REGION" \
  --project="$PROJECT_ID" \
  "${PUBLIC_ACCESS_ARGS[@]}" \
  --memory 2Gi \
  --cpu 1 \
  --timeout 300 \
  --concurrency 1 \
  --max-instances "$MAX_INSTANCES" \
  --set-env-vars "$RUNTIME_ENV_VARS" \
  --remove-secrets "$LEGACY_SECRET_ENV_KEYS" \
  --update-secrets "$RUNTIME_SECRET_MOUNTS"
