import Head from "next/head";

import ClientApp from "../src/ClientApp.jsx";

const SITE_URL = "https://www.aperiodos.com";
const ROUTES = {
  "/": {
    title: "Aperiodos – Aperiodic Tile Generators",
    description: "Create and export Einstein monotile, Spectre, and Penrose tiling patterns in your browser.",
  },
  "/einstein": {
    title: "Einstein Tile Generator – Aperiodic Monotile Tool | Aperiodos",
    description: "Create an Einstein aperiodic monotile pattern online. Adjust scale, colors, canvas size, and iterations, then export your tiling as SVG, PNG, or JPG.",
  },
  "/spectre": {
    title: "Spectre Tile Generator – Aperiodic Monotile Tool | Aperiodos",
    description: "Generate and export customizable aperiodic Spectre monotile patterns online.",
  },
  "/penrose": {
    title: "Penrose Tiling Generator – Kite, Dart, and Rhomb Patterns | Aperiodos",
    description: "Create Penrose tilings with kites and darts, rhombs, or star-rich patterns and export the result.",
  },
  "/studio": {
    title: "Einstein Material Studio – Design Tile Patterns | Aperiodos",
    description: "Design reusable Einstein tile materials on the native hexagonal lattice, preview rotations and reflections, and export SVG or JSON.",
  },
  "/sponsors": {
    title: "Sponsors | Aperiodos",
    description: "Meet the people and organizations supporting the free Aperiodos tile generators.",
  },
  "/donate": {
    title: "Support Aperiodos",
    description: "Support the free Aperiodos aperiodic tile generators.",
    canonicalPath: "/sponsors",
    noindex: true,
  },
  "/generation-codes": {
    title: "Generation Codes | Aperiodos",
    description: "Purchase generation codes for additional Aperiodos pattern renders.",
    noindex: true,
  },
  "/about": {
    title: "About Aperiodos – Aperiodic Tiling Tools",
    description: "Learn about Aperiodos, its aperiodic monotile generators, mathematical references, and implementation.",
  },
};

export default function Page({ path }) {
  const metadata = ROUTES[path] || ROUTES["/"];
  const canonicalUrl = `${SITE_URL}${metadata.canonicalPath || path}`;
  const structuredData = path === "/einstein" ? {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: "Einstein Tile Generator",
    url: canonicalUrl,
    applicationCategory: "DesignApplication",
    operatingSystem: "Any",
    browserRequirements: "Requires JavaScript",
    description: metadata.description,
    isAccessibleForFree: true,
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "EUR",
    },
  } : null;

  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta
          name="robots"
          content={metadata.noindex ? "noindex, follow" : "index, follow, max-image-preview:large"}
        />
        <link rel="canonical" href={canonicalUrl} />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Aperiodos" />
        <meta property="og:title" content={metadata.title} />
        <meta property="og:description" content={metadata.description} />
        <meta property="og:url" content={canonicalUrl} />
        <meta property="og:image" content={`${SITE_URL}/custom-pattern_1024.png`} />
        <meta property="og:image:alt" content="Colorful aperiodic monotile pattern generated by Aperiodos" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={metadata.title} />
        <meta name="twitter:description" content={metadata.description} />
        <meta name="twitter:image" content={`${SITE_URL}/custom-pattern_1024.png`} />
        {structuredData ? (
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
          />
        ) : null}
      </Head>
      <ClientApp />
    </>
  );
}

export function getStaticPaths() {
  return {
    paths: Object.keys(ROUTES),
    fallback: false,
  };
}

export function getStaticProps({ params }) {
  const segments = Array.isArray(params?.slug) ? params.slug : [];
  const path = segments.length ? `/${segments.join("/")}` : "/";
  return { props: { path } };
}
