export const DEFAULT_CANVAS_SIZE = 1024;

export const EINSTEIN_DEFAULTS = {
  iterations: 5,
  scale: 100,
  width: DEFAULT_CANVAS_SIZE,
  height: DEFAULT_CANVAS_SIZE,
  center_x: 0,
  center_y: 0,
  format: "png",
  color_mode: "translation",
  simple_color: "white",
  material_mode: "solid",
  pattern_style: "curves",
  pattern_design: "builtin:curves",
  pattern_base: "white",
  pattern_color: "#00c200",
  seed: "",
  color_h1: "black",
  color_h: "seagreen",
  color_t: "white",
  color_p: "sandybrown",
  color_f: "gold",
  four_color_1: "seagreen",
  four_color_2: "sienna",
  four_color_3: "goldenrod",
  four_color_4: "midnightblue",
  background: "white",
  outline: "black",
  stroke_width: 2
};

export const SPECTRE_DEFAULTS = {
  width: DEFAULT_CANVAS_SIZE,
  height: DEFAULT_CANVAS_SIZE,
  iterations: "",
  scale: 100,
  center_x: 0,
  center_y: 0,
  format: "svg",
  material_mode: "solid",
  pattern_design: "",
  color_mode: "translation",
  simple_color: "white",
  draw_mode: "translation",
  shape: "curved",
  background: "white",
  outline: "black",
  stroke_width: 1,
  palette_1: "seagreen",
  palette_2: "sienna",
  palette_3: "goldenrod",
  palette_4: "midnightblue"
};

export const PENROSE_DEFAULTS = {
  width: DEFAULT_CANVAS_SIZE,
  height: DEFAULT_CANVAS_SIZE,
  iterations: 4,
  scale: 100,
  center_x: 0,
  center_y: 0,
  format: "svg",
  build_logic: "default",
  tile_mode: "kite-dart",
  background: "white",
  outline: "black",
  stroke_width: 1,
  palette_1: "wheat",
  palette_2: "midnightblue",
  palette_3: "sandybrown",
  palette_4: "seagreen"
};
