import {
  DEFAULT_COLORS,
  DONATION_CURRENCIES,
  DEFAULT_FOUR_COLORS,
  DEFAULT_HTTP_HEIGHT,
  DEFAULT_HTTP_WIDTH,
  DEFAULT_ITERATIONS,
  DEFAULT_SCALE,
  donationCurrency,
  donationServiceAvailable,
  minimumDonationCents,
} from "../../src/server/config.js";
import { methodNotAllowed } from "../../src/server/http.js";

export default function handler(req, res) {
  if (req.method !== "GET") {
    return methodNotAllowed(res, ["GET"]);
  }
  return res.status(200).json({
    service: "aperiodos",
    status: "ok",
    frontend: "next",
    endpoints: {
      "GET /api": "API overview",
      "GET /api/healthz": "Basic health check",
      "GET /api/about": "References and acknowledgements",
      "GET /api/sponsors": "List public sponsors",
      "POST /api/donations/checkout-session": "Create a Stripe checkout session for a donation",
      "POST /api/render-credits/checkout-session": "Buy ten single-use generation codes",
      "POST /api/render-credits/confirm-session": "Confirm payment and issue generation codes",
      "GET /api/render-credits/email-status": "Check generation-code email delivery status",
      "POST /api/stripe/webhook": "Stripe webhook endpoint for recording paid sponsors",
      "POST /api/einstein/render": "Generate an Einstein image and return it directly",
      "POST /api/spectre/render": "Generate a Spectre SVG, PNG, or JPG and return it directly",
      "POST /api/penrose/render": "Generate a Penrose kite-dart, rhomb, or P1 SVG, PNG, or JPG and return it directly",
    },
    donations: {
      enabled: donationServiceAvailable(),
      currency: donationCurrency(),
      supported_currencies: DONATION_CURRENCIES,
      minimum_cents: minimumDonationCents(),
    },
    einstein_example_payload: {
      iterations: DEFAULT_ITERATIONS,
      width: DEFAULT_HTTP_WIDTH,
      height: DEFAULT_HTTP_HEIGHT,
      scale: DEFAULT_SCALE,
      center_x: 0,
      center_y: 0,
      colors: DEFAULT_COLORS,
      color_mode: "families",
      four_colors: DEFAULT_FOUR_COLORS,
      background: "white",
      no_outline: false,
      seed: null,
      format: "png",
    },
    spectre_example_payload: {
      width: DEFAULT_HTTP_WIDTH,
      height: DEFAULT_HTTP_HEIGHT,
      iterations: 5,
      auto_iterations: false,
      scale: DEFAULT_SCALE,
      center_x: 0,
      center_y: 0,
      format: "svg",
      draw_mode: "translation",
      shape: "curved",
      palette: ["#1f6a5d", "#b4552d", "#d8b24c", "#17313b"],
      background: "#ffffff",
      outline: "black",
      stroke_width: 1.2,
    },
    penrose_example_payload: {
      width: DEFAULT_HTTP_WIDTH,
      height: DEFAULT_HTTP_HEIGHT,
      iterations: 4,
      scale: DEFAULT_SCALE,
      center_x: 0,
      center_y: 0,
      format: "svg",
      build_logic: "default",
      tile_mode: "kite-dart",
      palette: ["wheat", "crimson"],
      background: "white",
      outline: "black",
      stroke_width: 1.0,
    },
  });
}
